import { expect, test } from "bun:test"
import { createRoot, createSignal } from "solid-js"
import { createListVisibility } from "../src/controllers/list-visibility"

test("list limits reveal all, collapse, and reset only on relevant changes", () => {
  createRoot((dispose) => {
    const [items, setItems] = createSignal([1, 2, 3, 4])
    const [limit, setLimit] = createSignal(0)
    const [key, setKey] = createSignal("target:query")
    const list = createListVisibility({ items, limit, resetKey: key })
    expect(list.visible()).toEqual(items())
    expect(list.canToggle()).toBe(false)
    setLimit(2)
    expect(list.visible()).toEqual([1, 2])
    expect(list.hiddenCount()).toBe(2)
    list.showAll()
    setItems([4, 3, 2, 1, 5])
    expect(list.visible()).toEqual(items())
    list.showLess()
    expect(list.visible()).toEqual([4, 3])
    list.showAll()
    setKey("other:query")
    expect(list.expanded()).toBe(false)
    list.showAll()
    setKey("other:new-query")
    expect(list.expanded()).toBe(false)
    list.showAll()
    setLimit(3)
    expect(list.visible()).toEqual([4, 3, 2])
    list.showAll()
    setItems([1, 2, 3])
    expect(list.canToggle()).toBe(false)
    setItems([1, 2, 3, 4])
    expect(list.expanded()).toBe(false)
    setItems([])
    expect(list.visible()).toEqual([])
    expect(list.canToggle()).toBe(false)
    dispose()
  })
})
