import type { Plugin } from '@opencode/plugin/tui'
import type { TuiThemeCurrent } from '@opencode-ai/plugin/tui'

export function legacyTheme(theme: Plugin.Context['theme']): TuiThemeCurrent {
  return {
    primary: theme.hue.interactive[200],
    secondary: theme.categorical[0]?.[200] ?? theme.hue.accent[200],
    accent: theme.hue.accent[200],
    error: theme.text.feedback.error.base,
    warning: theme.text.feedback.warning.base,
    success: theme.text.feedback.success.base,
    info: theme.text.feedback.info.base,
    text: theme.text.base,
    textMuted: theme.text.muted,
    selectedListItemText: theme.text.action.primary.focused,
    background: theme.background.base,
    backgroundPanel: theme.background.raised.base,
    backgroundElement: theme.background.raised.high,
    backgroundMenu: theme.background.raised.max,
    border: theme.border.base,
    borderActive: theme.scrollbar.base,
    borderSubtle: theme.hue.neutral[500],
    diffAdded: theme.diff.text.added,
    diffRemoved: theme.diff.text.removed,
    diffContext: theme.diff.text.context,
    diffHunkHeader: theme.diff.text.hunkHeader,
    diffHighlightAdded: theme.diff.highlight.added,
    diffHighlightRemoved: theme.diff.highlight.removed,
    diffAddedBg: theme.diff.background.added,
    diffRemovedBg: theme.diff.background.removed,
    diffContextBg: theme.diff.background.context,
    diffLineNumber: theme.diff.lineNumber.text,
    diffAddedLineNumberBg: theme.diff.lineNumber.background.added,
    diffRemovedLineNumberBg: theme.diff.lineNumber.background.removed,
    markdownText: theme.markdown.text,
    markdownHeading: theme.markdown.heading,
    markdownLink: theme.markdown.link,
    markdownLinkText: theme.markdown.linkText,
    markdownCode: theme.markdown.code,
    markdownBlockQuote: theme.markdown.blockQuote,
    markdownEmph: theme.markdown.emphasis,
    markdownStrong: theme.markdown.strong,
    markdownHorizontalRule: theme.markdown.horizontalRule,
    markdownListItem: theme.markdown.listItem,
    markdownListEnumeration: theme.markdown.listEnumeration,
    markdownImage: theme.markdown.image,
    markdownImageText: theme.markdown.imageText,
    markdownCodeBlock: theme.markdown.codeBlock,
    syntaxComment: theme.syntax.comment,
    syntaxKeyword: theme.syntax.keyword,
    syntaxFunction: theme.syntax.function,
    syntaxVariable: theme.syntax.variable,
    syntaxString: theme.syntax.string,
    syntaxNumber: theme.syntax.number,
    syntaxType: theme.syntax.type,
    syntaxOperator: theme.syntax.operator,
    syntaxPunctuation: theme.syntax.punctuation,
    thinkingOpacity: 0.6,
  }
}
